#cloud-config
# Cloud-init supports the creation of simple partition tables and file systems
# on devices.
# Data disks definitions for Microsoft Azure
# ------------------------------------------
runcmd:
    - echo "hello" >> /tmp/hello.txt